#include "pch.h"
#include "RenderConstants.h"

namespace Constants
{
	const UINT VERTEX_COUNT = 1000000;
	const UINT UPLOAD_BUFFER_SIZE = 10 * 1000 * 1000; //10Mb
	D3D12_RESOURCE_BARRIER PRESENT_TO_RT;
	D3D12_RESOURCE_BARRIER RT_TO_PRESENT;
	D3D12_RESOURCE_BARRIER TO_INDEX_BUFFER;


	void InitConstants()
	{
		PRESENT_TO_RT = {};
		PRESENT_TO_RT.Type = D3D12_RESOURCE_BARRIER_TYPE_TRANSITION;
		PRESENT_TO_RT.Transition.StateBefore = D3D12_RESOURCE_STATE_PRESENT;
		PRESENT_TO_RT.Transition.StateAfter = D3D12_RESOURCE_STATE_RENDER_TARGET;

		RT_TO_PRESENT = {};
		RT_TO_PRESENT.Type = D3D12_RESOURCE_BARRIER_TYPE_TRANSITION;
		RT_TO_PRESENT.Transition.StateAfter = D3D12_RESOURCE_STATE_PRESENT;
		RT_TO_PRESENT.Transition.StateBefore = D3D12_RESOURCE_STATE_RENDER_TARGET;

		TO_INDEX_BUFFER = {};
		TO_INDEX_BUFFER.Type = D3D12_RESOURCE_BARRIER_TYPE_TRANSITION;
		TO_INDEX_BUFFER.Transition.StateBefore = D3D12_RESOURCE_STATE_COPY_DEST;
		TO_INDEX_BUFFER.Transition.StateAfter = D3D12_RESOURCE_STATE_INDEX_BUFFER;
	}
}
